# Generated by Django 5.2.4 on 2026-01-24 21:12

import api.models.bill
import api.models.blog
import api.models.event
import api.utils
import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNDER_REVIEW", "Under Review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("INTERVIEWS", "Interviews"),
                        ],
                        default="UNDER_REVIEW",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recruitment Application",
                "verbose_name_plural": "Recruitment Applications",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "image",
                    models.ImageField(upload_to=api.models.bill.bill_image_upload_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name="InlineImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=api.models.blog.temp_inline_upload_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("start_time", models.TimeField(default=api.utils.current_time)),
                ("end_time", models.TimeField()),
                ("venue", models.CharField(max_length=50)),
                ("agenda", models.TextField(blank=True, null=True)),
                ("highlights", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecruitmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uni_session",
                    models.CharField(
                        help_text="Format: FAXX or SPXX (e.g., FA24, SP25)",
                        max_length=4,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="uni_session must start with 'FA' or 'SP' followed by 2 digits (e.g., FA24, SP25).",
                                regex="^(FA|SP)\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("application_start", models.DateField()),
                ("application_end", models.DateField()),
                ("interview_start", models.DateField()),
                ("interview_end", models.DateField()),
                ("result_date", models.DateField()),
            ],
            options={
                "verbose_name": "Recruitment Session",
                "verbose_name_plural": "Recruitment Sessions",
                "ordering": ["-application_start"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "student"),
                            ("LEAD", "lead"),
                            ("ADMIN", "admin"),
                        ],
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Pakistani number in the format +92XXXXXXXXXX.",
                                regex="\\+92[0-9]{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AcademicInfo",
            fields=[
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="academic_info",
                        serialize=False,
                        to="api.recruitmentapplication",
                    ),
                ),
                (
                    "reg_no",
                    models.CharField(
                        help_text="Student registration number", max_length=20
                    ),
                ),
                (
                    "current_semester",
                    models.IntegerField(
                        help_text="Current semester number (e.g., 1, 2, 3...)"
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[("BSCS", "bscs"), ("BSSE", "bsse"), ("BSAI", "bsai")],
                        max_length=10,
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="List of skills (stored as JSON array)"
                    ),
                ),
                (
                    "relevant_coursework",
                    models.JSONField(
                        default=list,
                        help_text="List of relevant courses (stored as JSON array)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Information",
                "verbose_name_plural": "Academic Information",
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="personal_info",
                        serialize=False,
                        to="api.recruitmentapplication",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        help_text="Valid email address required",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Pakistani number in the format +92XXXXXXXXXX.",
                                regex="^\\+92[0-9]{10}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Information",
                "verbose_name_plural": "Personal Information",
            },
        ),
        migrations.CreateModel(
            name="RolePreferences",
            fields=[
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="role_preferences",
                        serialize=False,
                        to="api.recruitmentapplication",
                    ),
                ),
                (
                    "preferred_role",
                    models.CharField(
                        choices=[
                            ("CODEHUB", "CodeHub"),
                            ("GRAPHICS_MEDIA", "Graphics & Media"),
                            ("SOCIAL_MEDIA_MARKETING", "Social Media and Marketing"),
                            ("REGISTRATION_DECOR", "Registration & Decor"),
                            ("EVENTS_LOGISTICS", "Events & Logistics"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "secondary_role",
                    models.CharField(
                        choices=[
                            ("CODEHUB", "CodeHub"),
                            ("GRAPHICS_MEDIA", "Graphics & Media"),
                            ("SOCIAL_MEDIA_MARKETING", "Social Media and Marketing"),
                            ("REGISTRATION_DECOR", "Registration & Decor"),
                            ("EVENTS_LOGISTICS", "Events & Logistics"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "join_purpose",
                    models.TextField(help_text="Why do you want to join ACM?"),
                ),
                (
                    "previous_experience",
                    models.TextField(
                        blank=True,
                        help_text="Any previous relevant experience",
                        null=True,
                    ),
                ),
                (
                    "weekly_availability",
                    models.CharField(
                        help_text="Available hours per week for ACM activities",
                        max_length=100,
                    ),
                ),
                (
                    "linkedin_profile",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profile URL (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Confirmation that all information is accurate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Preference",
                "verbose_name_plural": "Role Preferences",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=api.models.blog.blog_image_upload_path),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.blog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="/home/samtheradiant/PycharmProjects/ACM-CUI-Web/backend/media/events/default.png",
                        null=True,
                        upload_to=api.models.event.event_image_upload_path,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "present"),
                            ("ABSENT", "absent"),
                            ("LEAVE", "leave"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="api.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attending_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recruitmentapplication",
            name="recruitment_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="api.recruitmentsession",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(default="", max_length=20)),
                ("club", models.CharField(max_length=50)),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        default="profile_pics/default.jpg", upload_to="profile_pics/"
                    ),
                ),
                (
                    "profile_desc",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
