# Generated by Django 5.2.4 on 2026-01-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="application",
        ),
        migrations.RemoveField(
            model_name="recruitmentapplication",
            name="recruitment_session",
        ),
        migrations.RemoveField(
            model_name="rolepreferences",
            name="application",
        ),
        migrations.DeleteModel(
            name="AcademicInfo",
        ),
        migrations.DeleteModel(
            name="PersonalInfo",
        ),
        migrations.DeleteModel(
            name="RecruitmentSession",
        ),
        migrations.DeleteModel(
            name="RecruitmentApplication",
        ),
        migrations.DeleteModel(
            name="RolePreferences",
        ),
    ]
