# Generated by Django 5.2.4 on 2026-01-24 23:32

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_personalinfo_application_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNDER_REVIEW", "Under Review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("INTERVIEWS", "Interviews"),
                        ],
                        default="UNDER_REVIEW",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruitment Application",
                "verbose_name_plural": "Recruitment Applications",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uni_session",
                    models.CharField(
                        help_text="Format: FAXX or SPXX (e.g., FA24, SP25)",
                        max_length=4,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="uni_session must start with 'FA' or 'SP' followed by 2 digits (e.g., FA24, SP25).",
                                regex="^(FA|SP)\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("application_start", models.DateField()),
                ("application_end", models.DateField()),
                ("interview_start", models.DateField()),
                ("interview_end", models.DateField()),
                ("result_date", models.DateField()),
            ],
            options={
                "verbose_name": "Recruitment Session",
                "verbose_name_plural": "Recruitment Sessions",
                "ordering": ["-application_start"],
            },
        ),
        migrations.CreateModel(
            name="AcademicInfo",
            fields=[
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="academic_info",
                        serialize=False,
                        to="api.recruitmentapplication",
                    ),
                ),
                (
                    "reg_no",
                    models.CharField(
                        help_text="Student registration number", max_length=20
                    ),
                ),
                (
                    "current_semester",
                    models.IntegerField(
                        help_text="Current semester number (e.g., 1, 2, 3...)"
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[("BSCS", "bscs"), ("BSSE", "bsse"), ("BSAI", "bsai")],
                        max_length=10,
                    ),
                ),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "relevant_coursework",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Information",
                "verbose_name_plural": "Academic Information",
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="personal_info",
                        serialize=False,
                        to="api.recruitmentapplication",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        help_text="Valid email address required",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Pakistani number in the format +92XXXXXXXXXX.",
                                regex="^\\+92[0-9]{10}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Information",
                "verbose_name_plural": "Personal Information",
            },
        ),
        migrations.CreateModel(
            name="RolePreferences",
            fields=[
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="role_preferences",
                        serialize=False,
                        to="api.recruitmentapplication",
                    ),
                ),
                (
                    "preferred_role",
                    models.CharField(
                        choices=[
                            ("CODEHUB", "CodeHub"),
                            ("GRAPHICS_MEDIA", "Graphics & Media"),
                            ("SOCIAL_MEDIA_MARKETING", "Social Media and Marketing"),
                            ("REGISTRATION_DECOR", "Registration & Decor"),
                            ("EVENTS_LOGISTICS", "Events & Logistics"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "secondary_role",
                    models.CharField(
                        choices=[
                            ("CODEHUB", "CodeHub"),
                            ("GRAPHICS_MEDIA", "Graphics & Media"),
                            ("SOCIAL_MEDIA_MARKETING", "Social Media and Marketing"),
                            ("REGISTRATION_DECOR", "Registration & Decor"),
                            ("EVENTS_LOGISTICS", "Events & Logistics"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "join_purpose",
                    models.TextField(help_text="Why do you want to join ACM?"),
                ),
                (
                    "previous_experience",
                    models.TextField(
                        blank=True,
                        help_text="Any previous relevant experience",
                        null=True,
                    ),
                ),
                (
                    "weekly_availability",
                    models.CharField(
                        help_text="Available hours per week for ACM activities",
                        max_length=100,
                    ),
                ),
                (
                    "linkedin_profile",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profile URL (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Confirmation that all information is accurate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Preference",
                "verbose_name_plural": "Role Preferences",
            },
        ),
        migrations.AddField(
            model_name="recruitmentapplication",
            name="recruitment_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="api.recruitmentsession",
            ),
        ),
    ]
