# Generated by Django 5.2.4 on 2025-09-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_event_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
