# Generated by Django 5.2.4 on 2026-01-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_eventtype_alter_event_options_event_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="api_event_date_ec9874_idx",
        ),
        migrations.RemoveField(
            model_name="event",
            name="time",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="api_event_date_58da15_idx"),
        ),
    ]
