# Generated by Django 5.2.4 on 2026-01-24 22:39

import api.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/home/samtheradiant/PycharmProjects/ACM-CUI-Web/backend/media/events/default.png",
                null=True,
                upload_to=api.models.event.event_image_upload_path,
            ),
        ),
    ]
