# Generated by Django 5.2.4 on 2025-09-07 13:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_event_created_by_delete_attendance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("start_time", models.TimeField(default="01:25 PM")),
                ("end_time", models.TimeField()),
                ("venue", models.CharField(max_length=50)),
                ("agenda", models.TextField(blank=True, null=True)),
                ("highlights", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "present"),
                            ("ABSENT", "absent"),
                            ("LEAVE", "leave"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "meeting.py",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="api.meeting.py",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attending_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
