# Generated by Django 5.2.4 on 2025-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_meeting_meetingattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_desc",
            field=models.TextField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="student",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(default="05:38 PM"),
        ),
        migrations.AlterField(
            model_name="student",
            name="club",
            field=models.CharField(max_length=50),
        ),
    ]
