# Generated by Django 5.2.4 on 2026-01-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_recruitmentapplication_recruitmentsession_and_more"),
        ("api", "0004_event_image"),
    ]

    operations = []
