# Generated by Django 5.2.4 on 2025-09-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_student_profile_desc_student_profile_pic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="profile_desc",
        ),
        migrations.RemoveField(
            model_name="student",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="student",
            name="title",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(default="07:21 PM"),
        ),
    ]
