# Generated by Django 5.2.4 on 2026-01-25 21:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_20260125_2126"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, default=list, max_length=25),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="academicinfo",
            name="program",
            field=models.CharField(
                choices=[("BSCS", "Bscs"), ("BSSE", "Bsse"), ("BSAI", "Bsai")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="time_from",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="time_to",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rolepreferences",
            name="preferred_role",
            field=models.CharField(
                choices=[
                    ("CODEHUB", "Codehub"),
                    ("GRAPHICS", "Graphics"),
                    ("SOCIAL_MEDIA_MARKETING", "Social Media Marketing"),
                    ("MEDIA", "Media"),
                    ("DECOR", "Decor"),
                    ("EVENTS_LOGISTICS", "Events Logistics"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rolepreferences",
            name="secondary_role",
            field=models.CharField(
                choices=[
                    ("CODEHUB", "Codehub"),
                    ("GRAPHICS", "Graphics"),
                    ("SOCIAL_MEDIA_MARKETING", "Social Media Marketing"),
                    ("MEDIA", "Media"),
                    ("DECOR", "Decor"),
                    ("EVENTS_LOGISTICS", "Events Logistics"),
                ],
                max_length=30,
            ),
        ),
    ]
