# Generated by Django 5.2.4 on 2025-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_student_profile_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_desc",
            field=models.TextField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(
                default="profile_pics/default.jpg", upload_to="profile_pics/"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="title",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(default="12:56 PM"),
        ),
    ]
