# Generated by Django 5.2.4 on 2025-09-25 15:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_student_profile_desc_student_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(default=api.models.current_time),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_desc",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
