# Generated by Django 5.2.4 on 2025-11-17 16:58

import api.models.event
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani number in the format +92XXXXXXXXXX.', regex='\\+92[0-9]{10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, default='D:\\5th sem\\codehub-website\\backend\\media/events/default.png', null=True, upload_to=api.models.event.event_image_upload_path),
        ),
    ]
