# Generated by Django 5.2.4 on 2025-11-16 11:36

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="image",
            field=models.ImageField(
                default=None, upload_to=api.models.bill_image_upload_path
            ),
            preserve_default=False,
        ),
    ]
