# Generated by Django 5.2.4 on 2025-11-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_user_phone_number_alter_eventimage_image"),
        ("api", "0011_bill_image"),
    ]

    operations = []
