# Generated by Django 5.2.4 on 2025-11-22 10:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_merge_20251122_1020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/opt/codehub-website/backend/media/events/default.png",
                null=True,
                upload_to=api.models.event_image_upload_path,
            ),
        ),
    ]
