# Generated by Django 5.2.4 on 2025-11-22 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_eventimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Pakistani number in the format +92XXXXXXXXXX.",
                        regex="\\+92[0-9]{10}$",
                    )
                ],
            ),
        ),
    ]
