# Generated by Django 5.2.4 on 2025-11-30 07:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.blog.temp_inline_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, default='D:\\ACM-codehub\\codehub-website\\backend\\media/events/default.png', null=True, upload_to=api.models.event.event_image_upload_path),
        ),
    ]
