# Generated by Django 5.2.4 on 2025-12-05 16:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_inlineimage_alter_eventimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/opt/codehub-website/backend/media/events/default.png",
                null=True,
                upload_to=api.models.event_image_upload_path,
            ),
        ),
    ]
