# Generated by Django 5.2.4 on 2026-01-16 09:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_eventimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/home/hafeez/Downloads/codehub-website/codehub-website/backend/media/events/default.png",
                null=True,
                upload_to=api.models.event_image_upload_path,
            ),
        ),
    ]
